name: CKAN CI/CD
run-name: CKAN CI/CD [${{ github.ref_name == 'main' && 'prd' || 'hml' }}]

on:
  push:
    branches: [main, develop]

jobs:
  check-terraform-backend:
    name: Checks/Create Terraform Backend
    uses: ./.github/workflows/create-terraform-backend.yml
    secrets: inherit

  # check-docker-repository:
  #   name: Checks for Docker Repository
  #   runs-on: ubuntu-latest
  #   environment: ${{ github.ref_name }}
  #   steps:
  #     - if: ${{ !env.DOCKER_REPOSITORY_URL }}
  #       uses: ./github/workflows/docker/create-repository.yml
  #       env:
  #         DOCKER_REPOSITORY_URL: ${{ secrets.DOCKER_REPOSITORY_URL }}

  # build-docker-image:
  #   name: Build Docker image
  #   needs: check-docker-repository
  #   runs-on: ubuntu-latest
  #   environment: ${{ github.ref_name }}
  #   steps:
  #     - uses: ./.github/workflows/docker/build-image.yml
  #     secrets:
