name: CKAN CI/CD
run-name: CKAN CI/CD [${{ github.ref_name == 'main' && 'prd' || 'hml' }}]

on:
  push:
    branches: [main, develop]

jobs:
  check-terraform-backend:
    name: Checks/Create Terraform Backend
    uses: ./.github/workflows/create-terraform-backend.yml
    secrets: inherit

  check-container-repository:
    name: Checks for Container Repository
    uses: ./.github/workflows/create-repository.yml
    secrets: inherit
    needs: check-terraform-backend
